<?php
return array (
  'contents' => 
  array (
    0 => 
    array (
      'fieldid' => '30',
      'modelid' => '3',
      'field' => 'down_url',
      'name' => '下载地址',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '100',
      'errortips' => '下载地址不能为空',
      'fieldtype' => 'attachment',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    1 => 
    array (
      'fieldid' => '31',
      'modelid' => '3',
      'field' => 'copytype',
      'name' => '授权形式',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '20',
      'errortips' => '',
      'fieldtype' => 'select',
      'defaultvalue' => '',
      'setting' => '{\\"0\\":\\"\\\\u514d\\\\u8d39\\\\u7248\\",\\"1\\":\\"\\\\u6b63\\\\u5f0f\\\\u7248\\",\\"2\\":\\"\\\\u5171\\\\u4eab\\\\u7248\\",\\"3\\":\\"\\\\u8bd5\\\\u7528\\\\u7248\\",\\"4\\":\\"\\\\u6f14\\\\u793a\\\\u7248\\",\\"5\\":\\"\\\\u6ce8\\\\u518c\\\\u7248\\",\\"6\\":\\"\\\\u7834\\\\u89e3\\\\u7248\\"}',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    2 => 
    array (
      'fieldid' => '32',
      'modelid' => '3',
      'field' => 'systems',
      'name' => '平台',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '30',
      'errortips' => '',
      'fieldtype' => 'select',
      'defaultvalue' => '',
      'setting' => '{\\"0\\":\\"Windows\\",\\"1\\":\\"Linux\\",\\"2\\":\\"MacOS\\"}',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    3 => 
    array (
      'fieldid' => '33',
      'modelid' => '3',
      'field' => 'language',
      'name' => '语言',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '20',
      'errortips' => '',
      'fieldtype' => 'select',
      'defaultvalue' => '',
      'setting' => '{\\"0\\":\\"\\\\u7b80\\\\u4f53\\\\u4e2d\\\\u6587\\",\\"1\\":\\"\\\\u7e41\\\\u4f53\\\\u4e2d\\\\u6587\\",\\"2\\":\\"\\\\u82f1\\\\u6587\\",\\"3\\":\\"\\\\u591a\\\\u56fd\\\\u8bed\\\\u8a00\\",\\"4\\":\\"\\\\u5176\\\\u4ed6\\\\u8bed\\\\u8a00\\"}',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    4 => 
    array (
      'fieldid' => '34',
      'modelid' => '3',
      'field' => 'version',
      'name' => '版本',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '15',
      'errortips' => '版本号不能为空',
      'fieldtype' => 'input',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    5 => 
    array (
      'fieldid' => '35',
      'modelid' => '3',
      'field' => 'filesize',
      'name' => '文件大小',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '10',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    6 => 
    array (
      'fieldid' => '36',
      'modelid' => '3',
      'field' => 'classtype',
      'name' => '软件类型',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '30',
      'errortips' => '',
      'fieldtype' => 'radio',
      'defaultvalue' => '',
      'setting' => '{\\"0\\":\\"\\\\u56fd\\\\u4ea7\\\\u8f6f\\\\u4ef6\\",\\"1\\":\\"\\\\u56fd\\\\u5916\\\\u8f6f\\\\u4ef6\\",\\"2\\":\\"\\\\u6c49\\\\u5316\\\\u8865\\\\u4e01\\",\\"3\\":\\"\\\\u7a0b\\\\u5e8f\\\\u6e90\\\\u7801\\",\\"4\\":\\"\\\\u5176\\\\u4ed6\\"}',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    7 => 
    array (
      'fieldid' => '37',
      'modelid' => '3',
      'field' => 'stars',
      'name' => '评分等级',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '20',
      'errortips' => '',
      'fieldtype' => 'radio',
      'defaultvalue' => '',
      'setting' => '{\\"0\\":\\"\\\\u4e00\\\\u661f\\",\\"1\\":\\"\\\\u4e8c\\\\u661f\\",\\"2\\":\\"\\\\u4e09\\\\u661f\\",\\"3\\":\\"\\\\u56db\\\\u661f\\",\\"4\\":\\"\\\\u4e94\\\\u661f\\"}',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
  ),
  'expire' => 0,
  'mtime' => 1589653271,
);
?>