<?php
return array (
  'contents' => 
  array (
    0 => 
    array (
      'fieldid' => '40',
      'modelid' => '5',
      'field' => 'manager',
      'name' => '活动管理员',
      'tips' => '管理员用户名',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => 'tang',
      'setting' => '',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    1 => 
    array (
      'fieldid' => '41',
      'modelid' => '5',
      'field' => 'speakers',
      'name' => '讲师名单',
      'tips' => '讲师用户名, ;分割',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    2 => 
    array (
      'fieldid' => '42',
      'modelid' => '5',
      'field' => 'kankanurl',
      'name' => '默认背景',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '255',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => 'https://ssl.hongyanlv.com',
      'setting' => '',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    3 => 
    array (
      'fieldid' => '48',
      'modelid' => '5',
      'field' => 'start_time',
      'name' => '开始时间',
      'tips' => '',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'datetime',
      'defaultvalue' => '',
      'setting' => '1',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
  ),
  'expire' => 0,
  'mtime' => 1591094324,
);
?>