<?php
return array (
  'contents' => 
  array (
    'site_name' => '红研旅虚拟旅游研学平台',
    'site_url' => 'http://www.hongyanlv.com/',
    'site_keyword' => 'yzmcms,YzmCMS演示站,开源cms,cms系统',
    'site_description' => 'YzmCMS是一款基于YZMPHP开发的一套轻量级开源内容管理系统，YzmCMS简洁、安全、开源、实用，可运行在Linux、Windows、MacOSX、Solaris等各种平台上，专注为公司企业、个人站长快速建站提供解决方案。',
    'site_copyright' => 'Powered By YzmCMS内容管理系统 © 2014-2020 袁志蒙工作室',
    'site_filing' => '京ICP备666666号',
    'site_code' => '',
    'site_theme' => 'hongyanlv',
    'site_logo' => '',
    'url_mode' => '1',
    'is_words' => '0',
    'upload_maxsize' => '204800',
    'upload_types' => 'zip|rar|mp3|mp4',
    'ishtml5' => '1',
    'watermark_enable' => '0',
    'watermark_name' => 'mark.png',
    'watermark_position' => '9',
    'mail_server' => 'smtp.qq.com',
    'mail_port' => '25',
    'mail_from' => '',
    'mail_auth' => '1',
    'mail_user' => '',
    'mail_pass' => '',
    'mail_inbox' => '',
    'admin_log' => '0',
    'admin_prohibit_ip' => '',
    'prohibit_words' => '她妈|它妈|他妈|你妈|去死|贱人',
    'comment_check' => '0',
    'comment_tourist' => '0',
    'is_link' => '0',
    'member_register' => '1',
    'member_email' => '0',
    'member_check' => '0',
    'member_point' => '0',
    'member_yzm' => '1',
    'rmb_point_rate' => '10',
    'login_point' => '0',
    'comment_point' => '0',
    'publish_point' => '0',
    'qq_app_id' => 'f',
    'qq_app_key' => 'fr',
    'weibo_key' => '',
    'weibo_secret' => '',
    'wx_appid' => 'wx5924b84b866e1db9',
    'wx_secret' => 'f9607b5a464ebb9f5778cad79f53f287',
    'wx_token' => 'hood',
    'wx_encodingaeskey' => 'j4ZPgtQD2l80vt2FX24SOq7EGY73sou4P0OOF3YImUX',
    'wx_relation_model' => 'article',
    'baidu_push_token' => '',
    'thumb_width' => '500',
    'thumb_height' => '300',
    'search_page' => '10',
    'keyword_link' => '0',
    'keyword_replacenum' => '1',
  ),
  'expire' => 0,
  'mtime' => 1591816320,
);
?>