<?php
return array (
  'contents' => 
  array (
    '^activity$' => 'index/index/lists/catid/69',
    '^activity\\/list_(\\d+)$' => 'index/index/lists/catid/69/page/$1',
    '^teacher$' => 'index/index/lists/catid/70',
    '^teacher\\/list_(\\d+)$' => 'index/index/lists/catid/70/page/$1',
    '^minijidi$' => 'index/index/lists/catid/71',
    '^minijidi\\/list_(\\d+)$' => 'index/index/lists/catid/71/page/$1',
    '^article$' => 'index/index/lists/catid/72',
    '^article\\/list_(\\d+)$' => 'index/index/lists/catid/72/page/$1',
    '^article\\/(\\d+)$' => 'index/index/show/catid/72/id/$1',
    '^huodong\\/yuhuatai$' => 'index/index/lists/catid/74',
    '^huodong\\/yuhuatai\\/list_(\\d+)$' => 'index/index/lists/catid/74/page/$1',
    '^huodong\\/yuhuatai\\/(\\d+)$' => 'index/index/show/catid/74/id/$1',
    '^huodong\\/shanghailishibowuguan$' => 'index/index/lists/catid/75',
    '^huodong\\/shanghailishibowuguan\\/list_(\\d+)$' => 'index/index/lists/catid/75/page/$1',
    '^huodong\\/shanghailishibowuguan\\/(\\d+)$' => 'index/index/show/catid/75/id/$1',
    '^huodong\\/xibaipohuodong$' => 'index/index/lists/catid/76',
    '^huodong\\/xibaipohuodong\\/list_(\\d+)$' => 'index/index/lists/catid/76/page/$1',
    '^huodong\\/xibaipohuodong\\/(\\d+)$' => 'index/index/show/catid/76/id/$1',
    '^huodong\\/huabei$' => 'index/index/lists/catid/77',
    '^huodong\\/huabei\\/list_(\\d+)$' => 'index/index/lists/catid/77/page/$1',
    '^huodong\\/huabei\\/(\\d+)$' => 'index/index/show/catid/77/id/$1',
    '^jidi\\/yuhuatai$' => 'index/index/lists/catid/78',
    '^jidi\\/yuhuatai\\/list_(\\d+)$' => 'index/index/lists/catid/78/page/$1',
    '^jidi\\/yuhuatai\\/(\\d+)$' => 'index/index/show/catid/78/id/$1',
    '^jidi\\/shanghailishibowuguan$' => 'index/index/lists/catid/79',
    '^jidi\\/shanghailishibowuguan\\/list_(\\d+)$' => 'index/index/lists/catid/79/page/$1',
    '^jidi\\/shanghailishibowuguan\\/(\\d+)$' => 'index/index/show/catid/79/id/$1',
    '^jidi\\/xibaipo$' => 'index/index/lists/catid/80',
    '^jidi\\/xibaipo\\/list_(\\d+)$' => 'index/index/lists/catid/80/page/$1',
    '^jidi\\/xibaipo\\/(\\d+)$' => 'index/index/show/catid/80/id/$1',
    '^jidi\\/huabei$' => 'index/index/lists/catid/81',
    '^jidi\\/huabei\\/list_(\\d+)$' => 'index/index/lists/catid/81/page/$1',
    '^jidi\\/huabei\\/(\\d+)$' => 'index/index/show/catid/81/id/$1',
    '^jiangshi\\/yuhuatai$' => 'index/index/lists/catid/82',
    '^jiangshi\\/yuhuatai\\/list_(\\d+)$' => 'index/index/lists/catid/82/page/$1',
    '^jiangshi\\/yuhuatai\\/(\\d+)$' => 'index/index/show/catid/82/id/$1',
    '^jiangshi\\/shanghailishibowuguan$' => 'index/index/lists/catid/83',
    '^jiangshi\\/shanghailishibowuguan\\/list_(\\d+)$' => 'index/index/lists/catid/83/page/$1',
    '^jiangshi\\/shanghailishibowuguan\\/(\\d+)$' => 'index/index/show/catid/83/id/$1',
    '^jiangshi\\/xibaipo$' => 'index/index/lists/catid/84',
    '^jiangshi\\/xibaipo\\/list_(\\d+)$' => 'index/index/lists/catid/84/page/$1',
    '^jiangshi\\/xibaipo\\/(\\d+)$' => 'index/index/show/catid/84/id/$1',
    '^jiangshi\\/huabei$' => 'index/index/lists/catid/85',
    '^jiangshi\\/huabei\\/list_(\\d+)$' => 'index/index/lists/catid/85/page/$1',
    '^jiangshi\\/huabei\\/(\\d+)$' => 'index/index/show/catid/85/id/$1',
    '^huodong\\/gutianhuiyihuodong$' => 'index/index/lists/catid/86',
    '^huodong\\/gutianhuiyihuodong\\/list_(\\d+)$' => 'index/index/lists/catid/86/page/$1',
    '^huodong\\/gutianhuiyihuodong\\/(\\d+)$' => 'index/index/show/catid/86/id/$1',
    '^jiangshi\\/gutianhuiyi$' => 'index/index/lists/catid/87',
    '^jiangshi\\/gutianhuiyi\\/list_(\\d+)$' => 'index/index/lists/catid/87/page/$1',
    '^jiangshi\\/gutianhuiyi\\/(\\d+)$' => 'index/index/show/catid/87/id/$1',
    '^jidi\\/gutianhuiyi$' => 'index/index/lists/catid/88',
    '^jidi\\/gutianhuiyi\\/list_(\\d+)$' => 'index/index/lists/catid/88/page/$1',
    '^jidi\\/gutianhuiyi\\/(\\d+)$' => 'index/index/show/catid/88/id/$1',
  ),
  'expire' => 0,
  'mtime' => 1592211195,
);
?>