<?php
return array (
  'contents' => 
  array (
    0 => 
    array (
      'modelid' => '1',
      'name' => '文章',
      'tablename' => 'article',
      'description' => '文章',
      'setting' => '',
      'inputtime' => '1466393786',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '1',
    ),
    1 => 
    array (
      'modelid' => '2',
      'name' => '产品模型',
      'tablename' => 'product',
      'description' => '产品模型',
      'setting' => '',
      'inputtime' => '1466393786',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '1',
    ),
    2 => 
    array (
      'modelid' => '3',
      'name' => '下载模型',
      'tablename' => 'download',
      'description' => '下载模型',
      'setting' => '',
      'inputtime' => '1466393786',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '1',
    ),
    3 => 
    array (
      'modelid' => '5',
      'name' => '活动',
      'tablename' => 'activity',
      'description' => '活动',
      'setting' => '',
      'inputtime' => '1589729846',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '0',
    ),
    4 => 
    array (
      'modelid' => '6',
      'name' => '讲师',
      'tablename' => 'teacher',
      'description' => '讲师信息',
      'setting' => '',
      'inputtime' => '1589738622',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '0',
    ),
    5 => 
    array (
      'modelid' => '7',
      'name' => '资源',
      'tablename' => 'resource',
      'description' => '资源，包括图片，视频，全景图',
      'setting' => '',
      'inputtime' => '1590496059',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '0',
    ),
    6 => 
    array (
      'modelid' => '9',
      'name' => '基地',
      'tablename' => 'jd',
      'description' => '基地',
      'setting' => NULL,
      'inputtime' => '1591944120',
      'items' => '0',
      'disabled' => '0',
      'type' => '0',
      'sort' => '0',
      'issystem' => '0',
    ),
  ),
  'expire' => 0,
  'mtime' => 1592201603,
);
?>